import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    main: 'src/main.tsx',
    'puck-config': 'src/puck-config.ts',
    'page-schemas': 'src/page-schemas.ts',
    'data-schemas': 'src/data-schemas.ts',
    'site-styles': 'src/site-styles.ts',
    'mdx-components': 'src/mdx-components.ts',
    'mock-puck-config': 'src/mock-puck-config.tsx',
    ui: 'src/components/ui/index.ts',
    dialog: 'src/components/dialog.tsx',
    toast: 'src/components/toast.tsx',
  },
  format: ['esm'],
  dts: true,
  tsconfig: 'tsconfig.lib.json',
  clean: false,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    '@conloca/content-api',
    '@conloca/content-api-client',
    '@conloca/mdx',
    '@puckeditor/core',
    '@mdxeditor/editor',
    '@tanstack/react-query',
    '@tanstack/react-query-devtools',
    '@radix-ui/react-dialog',
    '@radix-ui/react-select',
    '@radix-ui/react-dropdown-menu',
    'react-router-dom',
    'lucide-react',
    'clsx',
    'tailwind-merge',
    'sonner',
    'sonner/dist/styles.css',
    'zod',
  ],
});
