import { createElement } from 'react'
import { hydrateRoot } from 'react-dom/client'

import type { HydrationStrategy } from '../types.js'

/**
 * Async loader function for a component.
 * Returns a module with a default export containing the React component.
 */
type ComponentLoader = () => Promise<{ default: React.ComponentType<unknown> }>

/**
 * Registry mapping component names to their async loaders.
 * Generated by the virtual:conloca-hydration-registry module at build time.
 */
export type ComponentRegistry = Record<string, ComponentLoader>

/**
 * Hydrate a single element with its corresponding React component.
 *
 * @param element - DOM element marked with data-hydrate attribute
 * @param registry - Component registry from virtual module
 */
async function hydrateElement(
  element: HTMLElement,
  registry: ComponentRegistry
): Promise<void> {
  const componentName = element.dataset.hydrate
  const propsJson = element.dataset.props || '{}'

  if (!componentName) {
    console.warn('[Conloca Hydration] Element missing data-hydrate attribute')
    return
  }

  const loader = registry[componentName]
  if (!loader) {
    console.warn(`[Conloca Hydration] Unknown component: ${componentName}`)
    return
  }

  try {
    const props = JSON.parse(propsJson)
    const { default: Component } = await loader()
    hydrateRoot(element, createElement(Component, props))

    // Clean up data attributes after successful hydration
    delete element.dataset.hydrate
    delete element.dataset.hydrateStrategy
    delete element.dataset.props
  } catch (error) {
    console.error(`[Conloca Hydration] Failed to hydrate ${componentName}:`, error)
  }
}

/**
 * Hydrate immediately on page load.
 */
function hydrateOnLoad(element: HTMLElement, registry: ComponentRegistry): void {
  hydrateElement(element, registry)
}

/**
 * Hydrate when element becomes visible in viewport.
 * Uses IntersectionObserver with 50px rootMargin for early loading.
 */
function hydrateOnVisible(element: HTMLElement, registry: ComponentRegistry): void {
  const observer = new IntersectionObserver(
    (entries, obs) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          obs.unobserve(entry.target)
          hydrateElement(entry.target as HTMLElement, registry)
        }
      }
    },
    { rootMargin: '50px' }
  )
  observer.observe(element)
}

/**
 * Hydrate when browser is idle.
 * Uses requestIdleCallback with setTimeout fallback for Safari.
 */
function hydrateOnIdle(element: HTMLElement, registry: ComponentRegistry): void {
  // Safari doesn't support requestIdleCallback, use setTimeout as fallback
  const scheduleIdle =
    window.requestIdleCallback ??
    ((cb: IdleRequestCallback) => window.setTimeout(() => cb({ didTimeout: false, timeRemaining: () => 50 }), 1))

  scheduleIdle(() => hydrateElement(element, registry), { timeout: 2000 })
}

/**
 * Initialize hydration for all marked components on the page.
 *
 * Finds all elements with [data-hydrate] attribute and hydrates them
 * according to their strategy (load, visible, idle).
 *
 * @param registry - Component registry mapping names to async loaders
 *
 * @example Usage with virtual module
 * ```typescript
 * import { initHydration } from '@conloca/astro-cms/lib/hydration-script'
 * import { componentRegistry } from 'virtual:conloca-hydration-registry'
 *
 * initHydration(componentRegistry)
 * ```
 */
export function initHydration(registry: ComponentRegistry): void {
  const elements = document.querySelectorAll<HTMLElement>('[data-hydrate]')

  for (const element of elements) {
    const strategy = (element.dataset.hydrateStrategy || 'load') as HydrationStrategy

    switch (strategy) {
      case 'load':
        hydrateOnLoad(element, registry)
        break
      case 'visible':
        hydrateOnVisible(element, registry)
        break
      case 'idle':
        hydrateOnIdle(element, registry)
        break
      default:
        // Default to load if strategy is unknown
        hydrateOnLoad(element, registry)
    }
  }
}
