import { createElement } from 'react'
import { hydrateRoot } from 'react-dom/client'

import type { HydrationStrategy } from '../types.js'

/**
 * Async loader that returns a React component.
 * The registry generator handles extraction from ComponentConfig at build time.
 */
type ComponentLoader = () => Promise<React.ComponentType<unknown>>

/**
 * Registry entry with loader and strategy.
 * Generated by the scanner from withHydration metadata.
 */
interface ComponentRegistryEntry {
  loader: ComponentLoader
  strategy: HydrationStrategy
}

/**
 * Registry mapping component names to their loaders and strategies.
 * Generated by virtual:conloca-hydration-registry at build time.
 */
export type ComponentRegistry = Record<string, ComponentRegistryEntry>

/**
 * Hydrate a single element with its corresponding React component.
 */
async function hydrateElement(
  element: HTMLElement,
  entry: ComponentRegistryEntry
): Promise<void> {
  const componentName = element.dataset.hydrate
  const propsJson = element.dataset.props || '{}'

  if (!componentName) {
    console.warn('[Conloca Hydration] Element missing data-hydrate attribute')
    return
  }

  try {
    const props = JSON.parse(propsJson)
    const Component = await entry.loader()
    hydrateRoot(element, createElement(Component, props))

    // Clean up data attributes after successful hydration
    delete element.dataset.hydrate
    delete element.dataset.hydrateStrategy
    delete element.dataset.props
  } catch (error) {
    console.error(`[Conloca Hydration] Failed to hydrate ${componentName}:`, error)
  }
}

/**
 * Hydrate immediately on page load.
 */
function hydrateOnLoad(element: HTMLElement, entry: ComponentRegistryEntry): void {
  hydrateElement(element, entry)
}

/**
 * Hydrate when element becomes visible in viewport.
 */
function hydrateOnVisible(element: HTMLElement, entry: ComponentRegistryEntry): void {
  const observer = new IntersectionObserver(
    (entries, obs) => {
      for (const ioEntry of entries) {
        if (ioEntry.isIntersecting) {
          obs.unobserve(ioEntry.target)
          hydrateElement(ioEntry.target as HTMLElement, entry)
        }
      }
    },
    { rootMargin: '50px' }
  )
  observer.observe(element)
}

/**
 * Hydrate when browser is idle.
 * Uses requestIdleCallback with setTimeout fallback for Safari.
 */
function hydrateOnIdle(element: HTMLElement, entry: ComponentRegistryEntry): void {
  const scheduleIdle =
    window.requestIdleCallback ??
    ((cb: IdleRequestCallback) => window.setTimeout(() => cb({ didTimeout: false, timeRemaining: () => 50 }), 1))

  scheduleIdle(() => hydrateElement(element, entry), { timeout: 2000 })
}

/**
 * Initialize hydration for all marked components on the page.
 *
 * Finds all elements with [data-hydrate] attribute and hydrates them
 * according to their strategy from the registry.
 */
export function initHydration(registry: ComponentRegistry): void {
  const elements = document.querySelectorAll<HTMLElement>('[data-hydrate]')

  for (const element of elements) {
    const componentName = element.dataset.hydrate
    if (!componentName) continue

    const entry = registry[componentName]
    if (!entry) {
      console.warn(`[Conloca Hydration] Unknown component: ${componentName}`)
      continue
    }

    // Use strategy from registry (set at build time via withHydration)
    const strategy = entry.strategy

    switch (strategy) {
      case 'load':
        hydrateOnLoad(element, entry)
        break
      case 'visible':
        hydrateOnVisible(element, entry)
        break
      case 'idle':
        hydrateOnIdle(element, entry)
        break
      default:
        hydrateOnLoad(element, entry)
    }
  }
}
