# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  bun-aarch64-darwin = {
    pname = "bun-aarch64-darwin";
    version = "1.2.18";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.18/bun-darwin-aarch64.zip";
      sha256 = "sha256-zKnrUnYrvYHriU/IJ1u6CgZU6BqtMY0ZhphUow83aaI=";
    };
  };
  bun-aarch64-linux = {
    pname = "bun-aarch64-linux";
    version = "1.2.18";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.18/bun-linux-aarch64.zip";
      sha256 = "sha256-G60WcdBboVaWMVynJI7AQ9KbWV/1+xX6hraZwiVdi8U=";
    };
  };
  bun-x86_64-darwin = {
    pname = "bun-x86_64-darwin";
    version = "1.2.18";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.18/bun-darwin-x64.zip";
      sha256 = "sha256-yD6k7yEmzJQgVv8ZWFGBgaKltnI9aqV8lrXQ+zTUt9w=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.2.18";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.18/bun-linux-x64.zip";
      sha256 = "sha256-kOAyqYKuKZxi1kXaxsqqjrALaQkryFAb8TpZDejQmcg=";
    };
  };
}
