/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --env-file=.dev.vars.example --include-runtime=false` (hash: fce2f9d3c751f25d399a82974e5c7ba3)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist-worker/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
