name = "conloca-website-dev"
main = "src/worker.ts"
compatibility_date = "2026-03-15"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

#--- Staging
[env.staging]
name = "conloca-website-staging"
workers_dev = false

[[env.staging.routes]]
pattern = "next.conloca.com"
custom_domain = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "conloca-website-staging-db"
migrations_dir = "migrations"
