name = "conloca-website"
main = "src/worker.ts"
compatibility_date = "2026-03-15"
workers_dev = false

[[routes]]
pattern = "conloca.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "conloca-website"
database_id = "1036447a-a3e7-460e-b666-921ef61c0a51"
migrations_dir = "migrations"
